
import javax.swing.JLabel;
import java.io.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Pranav
 */

public class compDash extends javax.swing.JFrame {
    

    /**
     * Creates new form emplDash
     */
//    public static emplDash instance;
//    public JLabel username;
//    static String username="";
//    public String uid="";
    public void myfun(String uid,String add,String email)
    {
        user.setText(uid);
//        name.setText(uid);
        userid.setText(uid);
        emailid.setText(email);
        addr.setText(add);
//        exp.setText(exp1);
//        uid=s;
    }
    public compDash() {
//        username=uname;
    initComponents();
//    instance=this;
//    username=user;
    
//        user.setText(uname);
        
    }
//    user.setText(username);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        user1 = new javax.swing.JLabel();
        userid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        addr = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        err = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));

        jLabel1.setText("Hello!");

        user.setText("Company Name");

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        user1.setText("Company");

        userid.setText("Company");

        jLabel2.setText("Email");

        emailid.setText("email");

        jLabel3.setText("Password");

        jLabel7.setText("Address");

        addr.setText("address");

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jButton1.setText("Jobs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4045060-removebg-preview-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userid)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addr, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(update)
                                .addGap(66, 66, 66)
                                .addComponent(jButton1)))
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(err, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(user)
                .addGap(166, 166, 166)
                .addComponent(Logout)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Logout)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userid, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(addr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(err, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
//        username="";
        Welcome reg=new Welcome();
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:


//        try
//        {
//
//            
//             String str,username,pass,email,fname,skills="",expr;
//             File file=new File("users.txt");
//             BufferedReader br1=new BufferedReader(new FileReader(file));
//             File temp=new File("temp.txt");
//             PrintWriter fw=new PrintWriter(temp);
//        username=userid.getText();
//        email=emailid.getText();
//        fname=name.getText();
//        expr=exp.getText();
//        pass=new String(password.getPassword());
//        if(chkJava.isSelected())skills+="JAVA#";
//        else skills+="#";
//        if(chkCpp.isSelected())skills+="C++#";
//        else skills+="#";
//        if(chkPy.isSelected())skills+="PYTHON#";
//        else skills+="#";
//            while((str=br1.readLine())!=null)
//            {
//                String[] result = str.split("\\|");
//                String uname1=result[0];
//
//            if(username.equals(uname1))
//            {
//                str=username+"|"+pass+"|"+fname+"|"+email+"|"+skills+"|"+expr+"|";
//                fw.write(str+"\n");
//                
//            }
//            else
//            {
//                fw.write(str+"\n");
//            }
//            
//            }
//            
//            br1.close();
//            fw.close();
//        br1.close();
//        file.delete();
//        temp.renameTo(file);
//        err.setText("Update Successful");
//        }
//        catch(Exception e)
//        {
//           err.setText(e.toString()); 
//        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
       
//        File file = new File("users.txt");
//        BufferedReader br = new BufferedReader(new FileReader(file));
//        
//        File temp = new File("temp.txt");
//        FileWriter pw = new FileWriter(temp);
//        
//        
//        username=userid.getText();
//        email=emailid.getText();
//        fname=name.getText();
//        expr=exp.getText();
//        pass=new String(password.getPassword());
//        if(chkJava.isSelected())skills+="JAVA#";
//        else skills+="#";
//        if(chkCpp.isSelected())skills+="C++#";
//        else skills+="#";
//        if(chkPy.isSelected())skills+="PYTHON#";
//        else skills+="#";
//
////        str=username+"|"+pass+"|"+fname+"|"+email+"|"+skills+"|"+expr+"|";
//        while((str= br.readLine()) !=null)
//        {
//        String[] result = str.split("\\|");
//        String uname=result[0];
//        if(uname.equals(username))
//        {
//         
//        str=username+"|"+pass+"|"+fname+"|"+email+"|"+skills+"|"+expr+"|";
////       
//        pw.write(str+"\n");
//        }
//        else
//        {
//        pw.write(str+"\n");
//        }
//        }
////        pw.flush();
//        pw.close();
//        br.close();
//        file.delete();
//        temp.renameTo(file);
//        System.out.println("File Modified");
////        file.close();
//        }
    
//    catch(Exception e){
//            err.setText(e.toString());
//    }   
        
        
        
        
        String str,username,pass,email,fname,skills="",add;
        username=userid.getText();
        email=emailid.getText();
//        fname=name.getText();
        add=addr.getText();
        pass=new String(password.getPassword());
//        if(chkJava.isSelected())skills+="JAVA#";
//        if(chkCpp.isSelected())skills+="C++#";
//        if(chkPy.isSelected())skills+="PYTHON#";

        
        try{
            
            File myfile=new File("company.txt");
            BufferedReader br=new BufferedReader(new FileReader(myfile));
            File temp=new File("temp.txt");
            FileWriter fw=new FileWriter(temp,true);
            
            
            
     

            
            while((str=br.readLine())!=null)
            {
                
                String[] result = str.split("\\|");
                String uname=result[0];
                if(uname.equals(username)){
                String str1=username+"|"+pass+"|"+add+"|"+email;
                fw.write(str1);
                }
                else
                fw.write(str);
                fw.write("\n");

             }
            fw.close();
//             pw.close();
        br.close();
        myfile.delete();
        temp.renameTo(myfile);
        System.out.println("File Modified");
        err.setText("Account Updated!");
        }
        catch(Exception e){
            err.setText(e.toString());
        }
    }//GEN-LAST:event_updateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Jobs reg=new Jobs();
        reg.myfun(userid.getText());
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emplDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emplDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emplDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emplDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emplDash().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JTextField addr;
    private javax.swing.JTextField emailid;
    private javax.swing.JLabel err;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton update;
    private javax.swing.JLabel user;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel userid;
    // End of variables declaration//GEN-END:variables
}
