
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Pranav
 */
public class EmplJob extends javax.swing.JFrame {

    /**
     * Creates new form EmplJob
     */
    public EmplJob() {
        initComponents();
    }
    String emplSkill1;
    int skillcount=0;
void myfun(String s,int c)
{
    emplSkill1=s;//User skills
    skillcount=c;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jobTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        jobTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company", "Position", "Experience", "Skills", "Location"
            }
        ));
        jScrollPane1.setViewportView(jobTable);

        jButton1.setText("LogOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/man-search-for-hiring-job-online-from-laptop-human-resources-management-concept-searching-professional-staff-free-vector__1_-removebg-preview.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("JOB SEARCH");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JOBS FOUND JUST FOR YOU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Refresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jButton1)
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Refresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        try{
            
            DefaultTableModel tbl=(DefaultTableModel)jobTable.getModel();
            tbl.getDataVector().removeAllElements();
            File file=new File("jobs.txt");
//            File temp=new File("temp.txt");
            // int flag=0;
            BufferedReader br=new BufferedReader(new FileReader(file));
//            PrintWriter pw=new PrintWriter(temp);
            String s,name,jpos,exp,skills,jloc;
            System.out.println("Enter usn to Modify ");
//            key=sc.nextLine();
            while((s=br.readLine())!=null)
            {
                int count=0;
                String res[]=s.split("\\|");
                name=res[1];
               jpos=res[2];
               exp=res[3];
              skills=res[4];//required skills for job
               jloc=res[5];
//               if(skills.charAt(0)=='#'){



//                    String trimSkill="";
//                    int flag=0;
//                for(int i=0;i<skills.length();i++)
//                {
//                    if(flag==0 && skills.charAt(i)!='#')flag=1;
//                    if(flag==1)trimSkill+=skills.charAt(i);
//                    
//                }
//                skills=trimSkill;
////                int pos=0;
//                int pos=0;
//                for(int i=skills.length()-1;i>=0;i--)
//                {
//                    if(skills.charAt(i)!='#'){pos=i+1;break;}
//                }
//                skills=skills.substring(0,pos+1);
                
                
                
                
                
//                }
               String skills2[]=skills.split("#");//job skills
//                if(key.equals(usn))
//                int x=0,y=0;
//                String s1=emplSkill[0],s2=skills2[0];
////                while(x<emplSkill.length && y<skills2.length)
//                    while(s1!=null && s2!=null)
//                {
//                    s1=emplSkill[x];s2=skills2[y];
//                if(s1.equals(s2))
//                {
//                count++;
//                x++;
//                y++;
//                }
//                else if(s1.compareTo(s2)<0)
//                x++;
//                else
//                y++;
//                }
//String common[]=new String[100];
                
//                if(emplSkill1.charAt(0)=='#'){





//                    trimSkill="";
//                    flag=0;
//                for(int i=0;i<emplSkill1.length();i++)
//                {
//                    if(flag==0 && emplSkill1.charAt(i)!='#')flag=1;
//                    if(flag==1)trimSkill+=emplSkill1.charAt(i);
//                    
//                }
//                emplSkill1=trimSkill;
//                pos=0;
//                for(int i=emplSkill1.length()-1;i>=0;i--)
//                {
//                    if(emplSkill1.charAt(i)!='#'){pos=i+1;break;}
//                }
//                emplSkill1=emplSkill1.substring(0,pos+1);
                
                
                
                
                
//                }

                String emplSkill[]=emplSkill1.split("#");//user skills
//		String skills2[]=skill1.split("#");
		String s1=emplSkill[0],s2=skills2[0];
		int x=0,y=0;
//                while(x<emplSkill.length && y<skills2.length)
                    while(x<emplSkill.length && y<skills2.length)
                {
                    s1=emplSkill[x];s2=skills2[y];
                if(s1.equals(s2))
                {
                    System.out.println(s1+" ");
//                    common[count]=s1;
                count++;
                x++;
                y++;
                }
                else if(s1.compareTo(s2)<0)
                x++;
                else
                y++;
                }






//                {
                    // flag=1;
                    String temp="";
                    for(int i=0;i<skills2.length;i++)temp+=skills2[i]+" ";
                    System.out.println("Job");
                    System.out.println(skills);
                    System.out.println(emplSkill1);
                    
                    String data[]={name,jpos,exp,temp,jloc}; 
                    if(count==skills2.length){
                        
                    tbl.addRow(data);
                    System.out.println("Common");
                    }
                    System.out.println("");

//                    pw.println(b); 
////                }
//                else pw.println(s);
            }
//            pw.close();
            br.close();
//            file.delete();
//            temp.renameTo(file);
            System.out.println("File Modified");


        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_RefreshActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Welcome reg=new Welcome();
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmplJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmplJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmplJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmplJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmplJob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Refresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jobTable;
    // End of variables declaration//GEN-END:variables
}
