
import javax.swing.JLabel;
import java.io.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Pranav
 */

public class emplDash extends javax.swing.JFrame {
    

    /**
     * Creates new form emplDash
     */
//    public static emplDash instance;
//    public JLabel username;
//    static String username="";
//    public String uid="";
    String emplSkill[]=new String[3];
    String emplSkill1;
    int skillcount=0;
    public void myfun(String uid,String name1,String email,String exp1,String skill)
    {
        user.setText("Hello!"+name1);
        pname.setText(name1);
        userid.setText(uid);
        emailid.setText(email);
        exp.setText(exp1);
        emplSkill1=skill;
//        uid=s;
    }
    public emplDash() {
//        username=uname;
    initComponents();
//    instance=this;
//    username=user;
    
//        user.setText(uname);
        
    }
//    user.setText(username);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        user1 = new javax.swing.JLabel();
        userid = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        emailid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        exp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        chkJava = new javax.swing.JCheckBox();
        chkCpp = new javax.swing.JCheckBox();
        chkPy = new javax.swing.JCheckBox();
        update = new javax.swing.JButton();
        err = new javax.swing.JLabel();
        ViewJobs = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        user2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));

        user.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        user.setText("Username");

        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        user1.setText("Username");

        userid.setText("User");

        jLabel5.setText("Name");

        pname.setText("name");
        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });

        jLabel2.setText("Email");

        emailid.setText("email");

        jLabel3.setText("Password");

        jLabel7.setText("Experience");

        exp.setText("in years");

        jLabel6.setText("Skills");

        chkJava.setText("Java");
        chkJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJavaActionPerformed(evt);
            }
        });

        chkCpp.setText("CPP");

        chkPy.setText("Python");

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        ViewJobs.setText("View Jobs");
        ViewJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewJobsActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/job-portal-development (1).png"))); // NOI18N

        user2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        user2.setText("User Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(user1))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userid)
                            .addComponent(exp, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(user2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)))
                                .addGap(199, 199, 199)
                                .addComponent(Logout))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(chkJava)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkCpp))
                                    .addComponent(update))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkPy)
                                        .addGap(109, 109, 109)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(ViewJobs)
                                        .addGap(80, 80, 80)
                                        .addComponent(err, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(17, 17, 17))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(user2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Logout)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user1)
                            .addComponent(userid))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(chkJava)
                            .addComponent(chkCpp)
                            .addComponent(chkPy)))
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update)
                            .addComponent(ViewJobs)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(err, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
//        username="";
        Welcome reg=new Welcome();
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:


//        try
//        {
//
//            
//             String str,username,pass,email,fname,skills="",expr;
//             File file=new File("users.txt");
//             BufferedReader br1=new BufferedReader(new FileReader(file));
//             File temp=new File("temp.txt");
//             PrintWriter fw=new PrintWriter(temp);
//        username=userid.getText();
//        email=emailid.getText();
//        fname=name.getText();
//        expr=exp.getText();
//        pass=new String(password.getPassword());
//        if(chkJava.isSelected())skills+="JAVA#";
//        else skills+="#";
//        if(chkCpp.isSelected())skills+="C++#";
//        else skills+="#";
//        if(chkPy.isSelected())skills+="PYTHON#";
//        else skills+="#";
//            while((str=br1.readLine())!=null)
//            {
//                String[] result = str.split("\\|");
//                String uname1=result[0];
//
//            if(username.equals(uname1))
//            {
//                str=username+"|"+pass+"|"+fname+"|"+email+"|"+skills+"|"+expr+"|";
//                fw.write(str+"\n");
//                
//            }
//            else
//            {
//                fw.write(str+"\n");
//            }
//            
//            }
//            
//            br1.close();
//            fw.close();
//        br1.close();
//        file.delete();
//        temp.renameTo(file);
//        err.setText("Update Successful");
//        }
//        catch(Exception e)
//        {
//           err.setText(e.toString()); 
//        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
       
//        File file = new File("users.txt");
//        BufferedReader br = new BufferedReader(new FileReader(file));
//        
//        File temp = new File("temp.txt");
//        FileWriter pw = new FileWriter(temp);
//        
//        
//        username=userid.getText();
//        email=emailid.getText();
//        fname=name.getText();
//        expr=exp.getText();
//        pass=new String(password.getPassword());
//        if(chkJava.isSelected())skills+="JAVA#";
//        else skills+="#";
//        if(chkCpp.isSelected())skills+="C++#";
//        else skills+="#";
//        if(chkPy.isSelected())skills+="PYTHON#";
//        else skills+="#";
//
////        str=username+"|"+pass+"|"+fname+"|"+email+"|"+skills+"|"+expr+"|";
//        while((str= br.readLine()) !=null)
//        {
//        String[] result = str.split("\\|");
//        String uname=result[0];
//        if(uname.equals(username))
//        {
//         
//        str=username+"|"+pass+"|"+fname+"|"+email+"|"+skills+"|"+expr+"|";
////       
//        pw.write(str+"\n");
//        }
//        else
//        {
//        pw.write(str+"\n");
//        }
//        }
////        pw.flush();
//        pw.close();
//        br.close();
//        file.delete();
//        temp.renameTo(file);
//        System.out.println("File Modified");
////        file.close();
//        }
    
//    catch(Exception e){
//            err.setText(e.toString());
//    }   
        try{
            File file=new File("users.txt");
            File temp=new File("temp.txt");
            // int flag=0;
            BufferedReader br=new BufferedReader(new FileReader(file));
            PrintWriter fw=new PrintWriter(temp);
            String s;
//            System.out.println("Enter usn to Modify ");
//            key=sc.nextLine();
            String str,username,pass,email,fname,skills="",expr;
        username=userid.getText();
        email=emailid.getText();
        fname=pname.getText();
        expr=exp.getText();
        pass=new String(password.getPassword());
        if(chkCpp.isSelected()){skills+="C++#";emplSkill[0]="CPP";skillcount++;}
//        else emplSkill[0]="-";
        if(chkJava.isSelected()){skills+="JAVA#";emplSkill[1]="JAVA";skillcount++;}
//        else emplSkill[1]="-";
        if(chkPy.isSelected()){skills+="PYTHON#";emplSkill[2]="PYTHON";skillcount++;}
//        if(checkSkill.isSelected()){skills+="Skill#";emplSkill[3]="CPP";skillcount++;}
//        else emplSkill[2]="-";
//            while((s=br.readLine())!=null)
//            {
                while((str=br.readLine())!=null)
            {
                
                String[] result = str.split("\\|");
                String uname=result[0];
                if(uname.equals(username)){
                String str1=username+"|"+pass+"|"+fname+"|"+email+"|"+skills+"|"+expr+"|";
                fw.println(str1);
                }
                else
                fw.println(str);

             
            }
//            }
            fw.close();
            br.close();
            file.delete();
            temp.renameTo(file);
            System.out.println("File Modified");


        
        }
        catch(Exception e)
        {
            System.out.println(e);
        }



        
        
        
        

        
//        try{
//             File here = new File(".");
//System.out.println(here.getAbsolutePath());
//            String str,username,pass,email,fname,skills="",expr;
//        username=userid.getText();
//        email=emailid.getText();
//        fname=pname.getText();
//        expr=exp.getText();
//        pass=new String(password.getPassword());
//        if(chkJava.isSelected())skills+="JAVA#";
//        if(chkCpp.isSelected())skills+="C++#";
//        if(chkPy.isSelected())skills+="PYTHON#";
//           
//            File myfile=new File("users.txt");
//            FileReader fr=new FileReader(myfile);
//            BufferedReader br=new BufferedReader(fr);
//            File temp=new File("temp.txt");
//            FileOutputStream fos=new FileOutputStream(temp,true);
//            PrintWriter fw=new PrintWriter(fos);
//            
//            
//            
//     
//
//            
//            while((str=br.readLine())!=null)
//            {
//                
//                String[] result = str.split("\\|");
//                String uname=result[0];
//                if(uname.equals(username)){
//                String str1=username+"|"+pass+"|"+fname+"|"+email+"|"+skills+"|"+expr+"|";
//                fw.println(str1);
//                }
//                else
//                fw.println(str);
//
//             }
//            fw.close();
////             pw.close();
//        br.close();
////        myfile.close();
//fos.close();
//fr.close();
//        myfile.delete();
//        temp.renameTo(myfile);
//        System.out.println("File Modified");
//        err.setText("Account Updated!");
//        }
//        catch(Exception e){
//            err.setText(e.toString());
//        }
    }//GEN-LAST:event_updateActionPerformed

    private void chkJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkJavaActionPerformed

    private void ViewJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewJobsActionPerformed
        // TODO add your handling code here:
        EmplJob reg=new EmplJob();
        reg.setVisible(true);
        reg.myfun(emplSkill1,skillcount);
        dispose();
        
                

                
    }//GEN-LAST:event_ViewJobsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emplDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emplDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emplDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emplDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emplDash().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton ViewJobs;
    private javax.swing.JCheckBox chkCpp;
    private javax.swing.JCheckBox chkJava;
    private javax.swing.JCheckBox chkPy;
    private javax.swing.JTextField emailid;
    private javax.swing.JLabel err;
    private javax.swing.JTextField exp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField pname;
    private javax.swing.JButton update;
    private javax.swing.JLabel user;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel user2;
    private javax.swing.JLabel userid;
    // End of variables declaration//GEN-END:variables
}
