/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.lang.String;
import java.io.*;
import javax.swing.WindowConstants;
/**
 *
 * @author Pranav
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }
    public static int count;
public static final int[] Address_list = new int[100];
public static final String[] uname_list = new String[100];

public int search_index(String key)
{
int low = 0, high = count, mid = 0;
    while(low <= high)
    {
    mid = (low + high)/2;
    if(uname_list[mid].equals(key))
    return mid;
    if(uname_list[mid].compareTo(key)>0)
        high = mid - 1;
    if(uname_list[mid].compareTo(key)<0)
        low = mid + 1;
    }
return -1;
}
//    System.out.println("\nNames in File:");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        SubmitBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        newAccBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        err = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SubmitBtn2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        userLabel1.setText("Username");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        passwordLabel.setText("Password");

        uname.setText("Username");

        pass.setText("abc123");

        SubmitBtn.setText("Login");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        ResetBtn.setText("Clear");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        newAccBtn.setText("SignUp");
        newAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Welcome");

        err.setForeground(new java.awt.Color(255, 0, 0));

        passwordLabel1.setText("Username");

        jLabel2.setText("User Login");

        SubmitBtn2.setText("Company Login");
        SubmitBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtn2ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/job-portal-development (1).png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(passwordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(98, 98, 98)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(uname)
                                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(jLabel2)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(err, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SubmitBtn)
                                .addGap(18, 18, 18)
                                .addComponent(ResetBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(SubmitBtn2)
                                .addGap(18, 18, 18)
                                .addComponent(newAccBtn))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubmitBtn)
                            .addComponent(ResetBtn)
                            .addComponent(newAccBtn)
                            .addComponent(SubmitBtn2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(err, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String uid,password;
    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        int flag=0;
        uid=uname.getText();
        password=new String(pass.getPassword());
        if(uid.equals("admin") && password.equals("abc123"))
        {
        Admin admin=new Admin();
        admin.setVisible(true);
        dispose();
        }
//        err.setText(uid+" "+password);
if(uid.isEmpty())err.setText("Username cannot be empty!");
else if(password.length()<=6)
{
    err.setText("Password must have atleast 6 characters");
    System.out.println(""+password.length());
}
else {
        try
        {
            count = -1;
            long pos;
            RandomAccessFile file = new RandomAccessFile("users.txt", "r");
            pos = file.getFilePointer();
            String s ;
            while((s = file.readLine())!=null)
            {
            String[] result = s.split("\\|");
            count++;
            uname_list[count] = result[0];
            Address_list[count] = (int)pos;
            pos=file.getFilePointer();
            }
         file.close();
            
    for(int i=0;i<=count;i++)
    {
        for(int j=i+1;j<=count;j++)
        {
            if(uname_list[i].compareTo(uname_list[j])>0)
            {
            String temp = uname_list[i];
            uname_list[i] = uname_list[j];
            uname_list[j] = temp;
            int temp1 = Address_list[i];
            Address_list[i]=Address_list[j];
            Address_list[j]=temp1;
            }
        }
    }
    int p=search_index(uid);
    if(p==-1)
    {
        err.setText("User Not Found!");
    }
    else
    {
        
  RandomAccessFile file1 = new RandomAccessFile("users.txt", "r");
int address = Address_list[p];
//String usn="",sem="",branch="",name="";      
        
        file1.seek(address);
String str = file1.readLine();
 String uname1="",password1="",name1="",email1="",skill="",exp="0";
while(str!=null)
{
String[] result = str.split("\\|");
uname1=result[0];
password1=result[1];
name1= result[2];
email1=result[3];
skill=result[4];
exp=result[5];

//branch = result[3];
//System.out.println("\nRecord Details");
//System.out.println("USN: " + usn);
//System.out.println("Name: " + name);
//System.out.println("Sem: " + sem);
//System.out.println("Branch: " + branch);
break;
}
file1.close();
if(password.length()<=6)
{
    err.setText("Password must have atleast 6 characters");
}
else if(uid=="")err.setText("Username cannot be empty!");
else if(password1.equals(password))
{
    err.setText("Login Successful!"); 
                Thread.sleep(500);
//                emplDash.instance.username.setText(uname.getText());
                emplDash emp=new emplDash();
                emp.myfun(uid,name1,email1,exp,skill);
//                emplDash reg=new Welcome();
                emp.setVisible(true);
//                file.close();
//                file1.close();
                dispose();
}
else err.setText("Invalid Password!");





    }
        }

        catch(Exception e)
        {
           err.setText(e.toString()); 
        }
}
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        uname.setText("");
        pass.setText("");
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void newAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccBtnActionPerformed
        // TODO add your handling code here:
        Register reg=new Register();
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_newAccBtnActionPerformed

    private void SubmitBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtn2ActionPerformed
        // TODO add your handling code here:
        compLogin reg=new compLogin();
        reg.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_SubmitBtn2ActionPerformed

    /**
     * @param args the command line arguments
     * 
     */
    void resize()
    {
        setTitle("FSProject");
        setSize(900,400);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
    }
    public void init()
        {
            setTitle("FSProject");
        setSize(900,400);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
        }
    public static void main(String args[]) {
        
//       resize();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Welcome().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JButton SubmitBtn2;
    private javax.swing.JLabel err;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newAccBtn;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JTextField uname;
    private javax.swing.JLabel userLabel1;
    // End of variables declaration//GEN-END:variables
}
